question_data = [
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "Niko Bellic is the protagonist of Grand Theft Auto IV.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Books",
                                           "question": "The book 1984 was published in 1949.", "correct_answer": "True",
                                           "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Television",
         "question": "In &quot;Star Trek&quot;, Klingons are aliens.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "In Splatoon, the Squid Sisters are named Tako and Yaki.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"type": "boolean", "difficulty": "easy", "category": "Sports",
                                          "question": "Roger Federer is a famous soccer player.",
                                          "correct_answer": "False",
                                          "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Politics",
         "question": "Donald Trump won the popular vote in the 2016 United States presidential election.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Cartoon &amp; Animations",
         "question": "Nickelodeon rejected the pilot to Adventure Time.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                                           "question": "The Great Wall of China is visible from the moon.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "&quot;Metal Gear Solid 3: Snake Eater&quot; takes place on Shadow Moses Island.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Geography",
         "question": "Ottawa is the capital of Canada.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Board Games",
         "question": "In the game &quot;Racko&quot; you may pick up ANY card from the discard pile.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "In Sonic the Hedgehog universe, Tails&#039; real name is Miles Prower.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Film",
                                           "question": "The color of the pills in the Matrix were Blue and Yellow.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
         "question": "Bugatti was an Italian car manufacturer.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Cartoon &amp; Animations",
         "question": "Night on Bald Mountain was one of the musical pieces featured in Disney&#039;s 1940&#039;s film Fantasia.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
         "question": "Soulja Boy&#039;s &#039;Crank That&#039; won a Grammy for Best Rap Song in 2007.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Mathematics",
         "question": "An isosceles triangle has two sides of equal length as opposed to three.",
         "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "easy", "category": "Animals",
                                           "question": "Kangaroos keep food in their pouches next to their children.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "Animals",
         "question": "Finnish Lapphund dogs were used for herding reindeer.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Mythology",
         "question": "A wyvern is the same as a dragon.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Politics",
         "question": "Despite being seperated into multiple countries, The Scandinavian countries are unified by all having the same monarch.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "History",
         "question": "Thomas Crapper was a plumber who invented the flushing toilet.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Geography", "question": "Tokyo is the capital of Japan.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "The character that would eventually become Dr. Eggman was considered for the role of Sega&#039;s new flagship mascot before Sonic was.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Mythology",
         "question": "In Greek mythology, Hera is the goddess of harvest.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Television",
         "question": "The Klingon home planet is Qo&#039;noS.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Japanese Anime &amp; Manga",
         "question": "In the &quot;Toaru Kagaku no Railgun&quot; anime,  espers can only reach a maximum of level 6 in their abilities.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "hard", "category": "History",
         "question": "The USS Missouri (BB-63) last served in the Korean War.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "In the &quot;Half-Life&quot; series, &quot;H.E.V&quot; stands for &quot;Hazardous Evasiveness Vest&quot;",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
         "question": "Igneous rocks are formed by excessive heat and pressure.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"type": "boolean", "difficulty": "easy", "category": "Science: Gadgets",
                                          "question": "Microphones can be used not only to pick up sound, but also to project sound similar to a speaker.",
                                          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Film",
         "question": "The movie &quot;Tron&quot; received an Oscar nomination for Best Visual Effects.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
         "question": "Fast food restaurant chains Carl&#039;s Jr. and Hardee&#039;s are owned by the same company.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
         "question": "When BMW was established in 1916, it was producing automobiles.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "In Monster Hunter Generations, guild style is a type of hunting style.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Japanese Anime &amp; Manga",
         "question": "Studio Ghibli is a Japanese animation studio responsible for the films &quot;Wolf Children&quot; and &quot;The Boy and the Beast&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "History",
         "question": "Martin Luther King Jr. and Anne Frank were born the same year. ", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
         "question": "&quot;The Division Bell&quot; is the final album of the progressive rock band Pink Floyd.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "Tony Hawk&#039;s Pro Skater was released in 1999.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "medium", "category": "History",
                                           "question": "The Hundred Years&#039; War was fought for more than a hundred years.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
         "question": "Metallica collaborated with Rowan Atkinson&#039;s Mr Bean on a 1992 comic relief single.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
         "question": "&quot;Typewriter&quot; is the longest word that can be typed using only the first row on a QWERTY keyboard.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
         "question": "Scottish producer Calvin Harris is from the town of Dumfries, Scotland.",
         "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "TF2: The Medic will be credited for an assist if he heals a Spy that successfully saps a building.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "In Heroes of the Storm, the Cursed Hollow map gimmick requires players to kill the undead to curse the enemy team.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
         "question": "Rapper Snoop Dogg&#039;s real name is &#039;Cordozar Calvin Broadus, Jr.&#039;.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Geography",
         "question": "You could walk from Norway to North Korea while only passing through Russia.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Television",
         "question": "Klingons express emotion in art through opera and poetry.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "medium", "category": "History",
                                           "question": "Adolf Hitler was accepted into the Vienna Academy of Fine Arts.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]}]
